<img src="https://numpy.org/_static/numpy_logo.png" width=50%>

# Ndarray对象

NumPy最重要的⼀个特点就是其**N维数组对象（即ndarray）**，该对象是⼀个快速⽽灵活的⼤数据（同种类型）集容器

## ndarray基本属性

比如以下数组a（实际上是一个**嵌套序列（nested sequence）**，但假设它是NumPy构造的array），我们要找到最大数10，用下标表示就是`a[1][1][0]`；于是我们说这是一个三维数组，有三个**轴(axes)**，三轴长度依次为：2，2，4

NumPy 数组的维数称为**秩（rank）**，一维数组的秩为 1，二维数组的秩为 2，以此类推

In [22]:
a=[[[1,2,3,4],[7,8,9,2]],[[4,5,6,7],[10,1,2,3]]]

In [23]:
a[1][1][0]

10

要构造一个ndarray类对象，需要了解它最基本的属性:

|Attribute|Description|
|:----:|:--------------:|
|ndim|轴数，即维度，a.ndim=3|
|shape|一个表示数组形状的元组，其元素为各轴长度，a.shape=(2,2,4)
|size|表述数组内元素总个数，a.size=2*2*4=16|
|dtype|元素类型,包括一些特有类型，如numpy.int32\int64\float64|
|itemsize|单个元素的字节，如int32为4字节|
|data|储存实际元素的缓冲器(buffer)，非常用属性|
|real|ndarray实部|
|imag|ndarray虚部|

In [24]:
import numpy as np
b=np.array(a)# 有嵌套序列a创建一个ndarray b
# 下面看看b的各个属性
print(b,type(b),b.real,b.imag,sep='\n')

[[[ 1  2  3  4]
  [ 7  8  9  2]]

 [[ 4  5  6  7]
  [10  1  2  3]]]
<class 'numpy.ndarray'>
[[[ 1  2  3  4]
  [ 7  8  9  2]]

 [[ 4  5  6  7]
  [10  1  2  3]]]
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


In [25]:
print(b.ndim,b.shape,b.size,b.dtype,b.itemsize,b.data,sep='\n')

3
(2, 2, 4)
16
int32
4


## **array**函数

创建一个 ndarray 只需调用 NumPy 的 array 函数即可，语法如下：

```Python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

参数说明如下：

|argument|Description|
|:----:|:--------------:|
|object|数组或嵌套的序列|
|dtype|同属性，可选|
|copy|对象是否需要复制，可选|
|order|创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）|
|subok|默认返回一个与基类类型一致的数组|
|ndmin|指定生成数组的最小维度|

In [66]:
import numpy as np 
a = np.array([1,2,3,4,5], ndmin =  2) 
b = np.array([1,2,3], dtype = complex)
print(a,b,sep='\n')

[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


此外，`array`还有一个“简易版”`asarray`，其参数减少到3个：
```Python
np.asarray(a, dtype=None, order=None)
```

In [67]:
a1 = np.asarray([1,2,3,4,5]) 
b1 = np.asarray([1,2,3], dtype = complex)
print(a1,b1,sep='\n')

[1 2 3 4 5]
[1.+0.j 2.+0.j 3.+0.j]


# 数组类型 

numpy 支持的数据类型比 Python 内置的类型要多很多，基本上可以和 C 语言的数据类型对应上，其中部分类型对应为 Python 内置的类型。下表列举了常用 NumPy 基本类型：

|dtype|Description|
|:----:|:--------------:|
|bool|布尔型，True/False|
|int*|有符号整型：8/16/32/64|
|uint*|无符号整型：8/16/32/64|
|float16|半精度浮点数，包括：1 个符号位，5 个指数位，10 个尾数位|
|float32|半精度浮点数，包括：1 个符号位，8 个指数位，23 个尾数位|
|float64|半精度浮点数，包括：1 个符号位，11 个指数位，52 个尾数位|
|complex64|复数，表示双 32 位浮点数（实数部分和虚数部分）|
|complex128|复数，表示双 64 位浮点数（实数部分和虚数部分）|

numpy 的数值类型实际上是 dtype 对象的实例，并对应唯一的字符，包括 np.bool_，np.int32，np.float32，等等

# 创建数组

前面我们介绍了**array**函数，除此之外，再介绍一些创建方法

## 特殊数组

### numpy.empty 

**numpy.empty** 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化(数组元素将为**随机值**)的数组:

```Python
numpy.empty(shape, dtype = float, order = 'C')
```

***order***有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序

In [51]:
import numpy as np 
E = np.empty((3,4), dtype =np.int16 ) 
E

array([[    0,     0,     0, 16368],
       [    0,     0,     0, 16384],
       [    0,     0,     0, 16392]], dtype=int16)

### numpy.zeros 

创建指定大小的数组，数组元素以 0 /False来填充：

In [52]:
Z=np.zeros((3,4), dtype =np.bool_ )
Z

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### numpy.ones 

创建指定形状的数组，数组元素以 1 来填充：

In [53]:
O=np.ones((3,4), dtype =np.float64)
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### numpy.eye

创建指定形状的**对角(diagonal)数组**，为什么用eye表示？因为通常我们用`I`表示单位阵，与eye谐音

```Python
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
```

这里的参数与前不同，N表示行；M表示列，默认为N，可选；k指的是对角线偏位值，如k=1,对角线右移1单位：

In [62]:
I=np.eye(3,5,1, dtype =int)
I

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

## 从已有的数组创建数组 

除了上文提到的**array**函数和**asarray**函数，我们还有别的选择

###  numpy.fromiter

numpy.fromiter 方法从可迭代对象(不仅限于**迭代器**)中建立 ndarray 对象，返回一维数组:
```Python
numpy.fromiter(iterable, dtype, count=-1)
```

***count***：读取的数据数量，默认为-1，读取所有数据

In [71]:
import numpy as np
# 利用iter函数创建一个itrator
it=iter([5,4,0,8,7])
x=np.fromiter(it, dtype=float)
x

array([5, 4, 0, 8, 7])

In [72]:
y=np.fromiter([5,4,0,8,7],dtype=int)
y

array([5, 4, 0, 8, 7])

## 从数值范围创建数组 

### numpy.arrange 

创建一维数组，函数语法如下，类似于普通的`range`函数，start默认为0，stop不含自身：
```Python
numpy.arange(start, stop, step, dtype)
```

In [74]:
import numpy as np
x = np.arange(10,20,2)  
x

array([10, 12, 14, 16, 18])

### numpy.linspace

`arrange`是以**步长step**限定输出，而`linspace`以**个数num**规定输出：
```Python
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
`endpoint`：该值为 ture 时，数列中中包含stop值，反之不包含

`restype`：如果为 True 时，将生成一个tuple，包含ndarray和step

In [87]:
x1 = np.linspace(10,20,5,endpoint=True,retstep=True)
x2 = np.linspace(10,20,5,endpoint=False)
print(x1,type(x1),sep='\n')
print(x2,type(x2),sep='\n')

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)
<class 'tuple'>
[10. 12. 14. 16. 18.]
<class 'numpy.ndarray'>


### numpy.logspace 

创建一个等比数列，并以`底数base`求真值数组
```Python
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```
`start`与`stop`：一维数组的起点/终点为：base<sup>start/stop</sup>

In [88]:
a = np.logspace(0,9,10,base=2)
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

# 切片和索引 

## 普通切片与slice函数

ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样

In [91]:
import numpy as np
a = np.arange(10)
s1= a[5] #索引
s2= a[2:8:3] #切片
s1,s2

(5, array([2, 5]))

另外，**`slice`**函数可以将切片过程分别进行：

In [97]:
s3 = slice(5)#stop=5
s4 = slice(2,8,3) 
a[s3],a[s4]

(array([0, 1, 2, 3, 4]), array([2, 5]))

## 多维数组切片 

多维数组同样适用上述索引提取方法：

In [131]:
b=np.empty(shape=(3,2,4),dtype=np.int16)
b

array([[[     0,      0,      0,  16420],
        [-29789, -17874, -23832,  16423]],

       [[  5958,  29789,  17873,  16427],
        [-23832,  11915,  -5958,  16430]],

       [[  5958,  29789,  17873,  16433],
        [ 23831, -11916,   5957,  16435]]], dtype=int16)

In [132]:
b[2] #在0轴上索引,此时shape=(2,4),降一维

array([[  5958,  29789,  17873,  16433],
       [ 23831, -11916,   5957,  16435]], dtype=int16)

In [133]:
b[2,1] #继续在第1轴上索引,shape=(4,)，再降一维

array([ 23831, -11916,   5957,  16435], dtype=int16)

加上**`...`**可以表示在该轴上遍取，该轴的维度保留

In [141]:
b[...,3] #shape=(3,2)，保留前两轴，去掉2轴所在的维度

array([[16420, 16423],
       [16427, 16430],
       [16433, 16435]], dtype=int16)

In [135]:
b[1,...,1] #shape=(2,),只保留第1轴所在的维度

array([29789, 11915], dtype=int16)

# 高级索引 

## 整数数组索引

从下列可以看出，数组作为索引，相当于对每一个轴上的元素进行**压缩**，即：X\[ax1,ax2,ax3,\...]

In [208]:
import numpy as np
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]]) 
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [145]:
# 找到四个角点的两轴坐标，进行压缩：
x[[0,0,3,3],[0,2,0,2]]

array([ 0,  2,  9, 11])

In [150]:
# 还可以改变轴的shape,输出对应shape的索引值
axis0=np.array([[0,0],[3,3]])
axis1=[[0,2],[0,2]]
x[axis0,axis1]

array([[ 0,  2],
       [ 9, 11]])

同样，可以借助切片**`:`**或**`…`**与索引数组组合：

In [151]:
x[...,1:]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

此外，还可以改变**索引顺序**或**倒序**：

In [215]:
print(x[[3,0,1,2]],x[[-1,-2,-3,-4]],sep='\n')

[[ 9 10 11]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]
[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]


## 布尔索引 

布尔索引通过布尔运算（**如：比较运算符**）来获取符合指定条件的元素的数组。如下例展示了一个构造**Boolean array**的方法：

```Ipython
>>>import numpy as np 
>>>x = np.arange(6).reshape(2,3)
>>>x
array([[0, 1, 2],
       [3, 4, 5]])
>>>y=x>3
>>>y #y是一个Boolean array
array([[False, False, False],
       [False,  True,  True]])
>>>x[y]
array([ 4,  5])
```

In [204]:
#构造一个包含NaN(not a number)的数组a，层层筛分出奇数元素
a = np.array([np.nan,1,2,np.nan,3,4,3+5j])
a

array([nan+0.j,  1.+0.j,  2.+0.j, nan+0.j,  3.+0.j,  4.+0.j,  3.+5.j])

In [205]:
#第一步。过滤掉NaN
b=~np.isnan(a)
a=a[b]
print(b,a,sep='\n')

[False  True  True False  True  True  True]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 3.+5.j]


In [206]:
#第二步，过滤掉虚部不为0的复数
a=a[~np.iscomplex(a)]
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [207]:
#第三步，过滤掉实部为偶数的复数
a=a[a.real%2!=0]
a

array([1.+0.j, 3.+0.j])

## **ix_()**函数

例如我们对一个矩阵进行**行列交换**运算，可以用到**`ix()_`**函数

In [217]:
import numpy as np 
x=np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [219]:
# 对上面的矩阵先做行变换，再做列变换
x[np.ix_([0,2,3,1],[1,0,3,2])]

array([[ 1,  0,  3,  2],
       [ 9,  8, 11, 10],
       [13, 12, 15, 14],
       [ 5,  4,  7,  6]])